### ISSUE TITLE
Error while fine-tunning

### ISSUE THREAD

**Issue by Luffy241** [AnswerDotAI/RAGatouille#244]
Hi Guys,

**I am trying to finetune the colbert using the reference from** -- _examples/02-basic_training.ipynb._
But i encountered the below issue while doing that.
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/luffy/.local/lib/python3.10/site-packages/colbert/infra/launcher.py", line 134, in setup_new_process
    return_val = callee(config, *args)
  File "/home/luffy/.local/lib/python3.10/site-packages/colbert/training/training.py", line 146, in train
    ckpt_path = manage_checkpoints(config, colbert, optimizer, batch_idx+1, savepath=None, consumed_all_triples=True)
UnboundLocalError: local variable 'batch_idx' referenced before assignment

I am using putty ( Ubuntu 22.04.4 LTS ) with AWS A100 GPU.
Also is there any parameter options related to multiprocessing. I feel it would be great if there is any blog to explain about the available parameter options along with explanations.

**Comment by bclavie** [comment]
Hey! Sorry about this, training hasn't gotten much love and it'll be overhauled in September (hopefully!) or by mid October, which will make it a lot easier. This particular bug isn't actually a RAGatouille issue -- it's related to a bug in the `colbert-ai` library referenced on issues over there, and which will be fixed in the upcoming release!
